import {flushPromises, mount } from '@vue/test-utils'
import Detailpage from '../../src/views/Detailpage/Detailpage.vue'

test('detailpage', async () => {
    const wrapper = mount(Detailpage, {})
    
    expect(wrapper.find('#item-title').text()).toBe('Lorem Ipsum V.1byevermotion')
    expect(wrapper.find('#item-price').text()).toBe('$144')
    // expect(wrapper.find('.text-license').text()).toBe('3D Model License:')
    expect(wrapper.find('#license-content').text()).toBe('3D Model License: Standard')
    expect(wrapper.find('#upgrade-license').text()).toBe('Upgrade License')
    expect(wrapper.find('#section2-title').text()).toBe('FORMATS')
    expect(wrapper.find('#format-content1').text()).toBe('3ds Max 2011 | V-ray 3.0')
    expect(wrapper.find('#format-content2').text()).toBe('3ds Max 2011 | V-ray 3.0')
    expect(wrapper.find('#format-content3').text()).toBe('3ds Max 2011 | V-ray 3.0')
    expect(wrapper.find('#format-content4').text()).toBe('3ds Max 2011 | V-ray 3.0')
    expect(wrapper.find('#format-tag1').text()).toBe('Others')
    expect(wrapper.find('#format-tag2').text()).toBe('3D')
    expect(wrapper.find('#format-tag3').text()).toBe('Anim')
    expect(wrapper.find('#previews-title').text()).toBe('PREVIEWS')
    expect(wrapper.find('#previews-content1').text()).toBe('file 1')
    expect(wrapper.find('#previews-content2').text()).toBe('file 2')
    expect(wrapper.find('#previews-content3').text()).toBe('file 3')
    expect(wrapper.find('#model-item1').text()).toBe('Others')
    expect(wrapper.find('#model-item2').text()).toBe('3D')
    expect(wrapper.find('#model-item3').text()).toBe('Anim')
    expect(wrapper.find('#model-item4').text()).toBe('Others')
    expect(wrapper.find('#model-item5').text()).toBe('3D')
    expect(wrapper.find('#model-item6').text()).toBe('Anim')
    expect(wrapper.find('#product-id').text()).toBe('Product ID: 1072838')
    expect(wrapper.find('#product-date').text()).toBe('Apr 14, 2016')
    expect(wrapper.find('#company-title').text()).toBe('By Evermotion')
    expect(wrapper.find('#total-products').text()).toBe('1929 Products')
    expect(wrapper.find('#total-date').text()).toBe('since 2000')
    expect(wrapper.find('#benefit1').text()).toBe('best price')
    expect(wrapper.find('#benefit2').text()).toBe('simple returns')
    expect(wrapper.find('#benefit3').text()).toBe('best protection')
    expect(wrapper.find('#benefit-question').text()).toBe('Have questions? Chat with us now.')
    expect(wrapper.find('#breadcrumbs').text()).toBe('bootstrap breadcrumbs')
    expect(wrapper.find('#description-products').text()).toBe(`Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.`)
    expect(wrapper.find('#description-tags').text()).toBe('product tags')
    expect(wrapper.find('#description-report').text()).toBe('product report')
    expect(wrapper.find('#related-products').text()).toBe('RELATED PRODUCTS')
    expect(wrapper.find('img[alt="Empty"]').attributes().src).toBe('https://picsum.photos/600/600')
    expect(wrapper.find('img[alt="Empty1"]').attributes().src).toBe('https://picsum.photos/75/75')
    expect(wrapper.find('img[alt="related-products1"]').attributes().src).toBe('https://picsum.photos/400/200')
    expect(wrapper.find('img[alt="related-products2"]').attributes().src).toBe('https://picsum.photos/400/200')
    expect(wrapper.find('img[alt="related-products3"]').attributes().src).toBe('https://picsum.photos/400/200')
    expect(wrapper.find('img[alt="related-products4"]').attributes().src).toBe('https://picsum.photos/400/200')
    expect(wrapper.find('img[alt="related-products5"]').attributes().src).toBe('https://picsum.photos/400/200')

    await flushPromises()
    await flushPromises()
    await flushPromises()
    await flushPromises()

    await wrapper.find('.btn-next').trigger('click')
})